docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
      - 'Routing': routing.md
      - 'Default Services': services.md
    - Migration:
      - 'Version 2 to Version 3': migration/v2-to-v3.md
site_name: laminas-mvc-i18n
site_description: Laminas\Mvc\I18n
repo_url: 'https://github.com/laminas/laminas-mvc-i18n'
